swagger: '2.0'
info:
  title: learntechpuzz-api
  version: 1.0.0
schemes:
  - https
consumes:
  - application/json  
produces:
  - application/json
paths:
  /user:
    post:
      x-amazon-apigateway-request-validator: all
      parameters:
        - in: "header"
          name: "Authorization"
          required: true
          type: "string"
        - in: "body"
          name: "User"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/ApiResponse'
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      security:
        - ApiCognitoAuthorizer: []              
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserFunction.Arn}/invocations
        responses:
          default:
            statusCode: 200
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
securityDefinitions:
  ApiCognitoAuthorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: cognito_user_pools
    x-amazon-apigateway-authorizer:
      type: cognito_user_pools
      providerARNs:
        - Fn::Sub: ${UserPool.Arn}
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      mobile:
        type: string
    required:
      - id
      - name
      - email
      - mobile
  ApiResponse:
    type: object
    properties: {}
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true    