openapi: "3.0.1"
info:
  title: learntechpuzz-api
  version: 1.0.0
paths:
  /user:
    post:
      x-amazon-apigateway-request-validator: all
      requestBody:
         description: A JSON object containing user information
         required: true
         content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      parameters:
        - in: "header"
          name: "Authorization"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Successful operation"
          headers:
            Access-Control-Allow-Headers:
              $ref: "#/components/headers/Access-Control-Allow-Headers"
            Access-Control-Allow-Methods:
              $ref: "#/components/headers/Access-Control-Allow-Methods"
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"          
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        400:
          description: "Invalid request body"
          headers:
            Access-Control-Allow-Headers:
              $ref: "#/components/headers/Access-Control-Allow-Headers"
            Access-Control-Allow-Methods:
              $ref: "#/components/headers/Access-Control-Allow-Methods"
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"          
          content: {}
        500:
          description: "Internal server error"
          headers:
            Access-Control-Allow-Headers:
              $ref: "#/components/headers/Access-Control-Allow-Headers"
            Access-Control-Allow-Methods:
              $ref: "#/components/headers/Access-Control-Allow-Methods"
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"          
          content: {}
      security:
        - ApiCognitoAuthorizer: []              
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserFunction.Arn}/invocations  
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: 
                schema:
                  $ref: "#/components/schemas/ApiResponse"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
components:
  headers:
    Access-Control-Allow-Headers:
      description: Access-Control-Allow-Headers
      schema:
        type: string
    Access-Control-Allow-Methods:
      description: Access-Control-Allow-Methods
      schema:
        type: string
    Access-Control-Allow-Origin:
      description: Access-Control-Allow-Origin
      schema:
        type: string
  securitySchemes:
    ApiCognitoAuthorizer:
      type: apiKey
      name: method.request.header.Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Fn::Sub: ${UserPool.Arn}
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        mobile:
          type: string
      required:
        - username
        - name
        - email
        - mobile
    ApiResponse:
      type: object
      properties:
        message:
          type: string
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true    